# Site settings
title: Scassandra Java Client
email: christopher.batey@gmail.com
description: "testing Cassandra applications from Java"
baseurl: "/java-client"
url: "http://scassandra.org/java-client"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: pretty
